---
  - name: Delete local files for inventory
    delegate_to: localhost
    file:
      path: "~/percona_aws/ansible/{{item}}"
      state: absent
    with_items:
      - aws_inventory.yml
      - private_ips.yml

  - name: Get Instance IDs from AWS Tags
    community.aws.ec2_instance_info:
      region: "{{region}}"
      filters:
        "tag:Name": "{{item}}"
    with_items: "{{instance_names}}"
    register: ec2_info

  - name: Terminate EC2s matching Tag Names
    delegate_to: localhost
    amazon.aws.ec2:
      region: "{{region}}"
      instance_ids: "{{item.instances[0].instance_id}}"
      state: absent
      wait: yes
    loop: "{{ec2_info.results}}"
    no_log: true