---
- name: Import create_security_group
  import_tasks: create_security_group.yml
  tags:
    - sg
    - never

- name: Import create_base_ec2s
  import_tasks: create_base_ec2s.yml
  tags:
    - ec2
    - never

- name: Setup Ansible Inventory
  import_tasks: setup_inventory.yml
  tags:
    - inventory
    - never

- name: Import percona_bootrap
  import_tasks: percona_bootstrap.yml
  tags:
    - bootstrap
    - never

- name: Import db_post_install
  import_tasks: db_post_install.yml
  tags:
    - post_install
    - never