galaxy_info:
  author: Jey Farmer
  description: AWS Role for Manipulating Percona Servers on AWS
  company: N/A
  license: MIT
  min_ansible_version: 2.11
  galaxy_tags:
    - percona
  dependencies:
    - boto3
    - amazon.aws
